name: swifty_gallery_cleaner

description: Swifty - Akıllı Galeri Temizleyici. Fotoğraf ve videolarınızı kolayca yönetin, düzenleyin ve temizleyin. Duplicate fotoğrafları bulun, gereksiz dosyaları silin ve galerinizi organize edin.

publish_to: 'none'

version: 1.2.7+14

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  photo_manager: ^3.0.0
  flutter_card_swiper: ^6.0.0

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  google_ml_kit: ^0.20.0
  path_provider: ^2.1.5
  video_player: ^2.9.5
  flutter_launcher_icons: ^0.14.4

  intl: ^0.20.2
  shared_preferences: ^2.2.2 # Galeri izni durumu için eklendi, sorun olursa kaldır.

dev_dependencies:
  flutter_test:
    sdk: flutter
  # intl_utils kaldırıldı

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logom.png"
  adaptive_icon_background: "#B24592"
  adaptive_icon_foreground: "assets/logom.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logom.png 